name: BuildTek
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  toastification: ^3.0.2
  go_router: ^15.1.1
  logger: ^2.5.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
